services:
  db:
    image: postgres:15
    container_name: main_db
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    environment:
      - TZ=Europe/Moscow
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
    container_name: main_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - huggingface_cache:/root/.cache/huggingface
    depends_on:
      db:
        condition: service_healthy
      django_migrations:
        condition: service_completed_successfully
      admin:
        condition: service_started

  django_migrations:
    build: ./admin_panel
    container_name: django_migration_runner
    env_file:
      - ./Backend/.env
    volumes:
      - ./admin_panel:/app
    depends_on:
      db:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        python manage.py migrate &&
        python manage.py createsuperuser --noinput || true &&
        python manage.py shell -c "from django.contrib.auth.models import Group; Group.objects.get_or_create(name='admin'); Group.objects.get_or_create(name='teacher');"

  alembic_migrations:
    build: ./Backend
    container_name: alembic_migration_runner
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head

  admin:
    build: ./admin_panel
    container_name: main_admin
    restart: always
    env_file:
      - ./Backend/.env
    ports:
      - "8001:8000"
    volumes:
      - ./admin_panel:/app
    depends_on:
      db:
        condition: service_healthy
      django_migrations:
        condition: service_completed_successfully

  frontend:
    build: .
    container_name: main_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  dozzle:
    image: amir20/dozzle:latest
    container_name: main_dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    restart: always

volumes:
  postgres_data:
  huggingface_cache: