services:
  db:
    image: postgres:15
    container_name: main_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: diplom_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    container_name: main_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/diplom_db
    depends_on:
      - db

volumes:
  postgres_data: