"""Initial migration

Revision ID: 22dd614885ee
Revises: 
Create Date: 2026-04-10 16:02:27.174104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dd614885ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('id_discipline', sa.Integer(), nullable=False),
    sa.Column('name_discipline', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_discipline')
    )
    op.create_index(op.f('ix_disciplines_id_discipline'), 'disciplines', ['id_discipline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciplines_id_discipline'), table_name='disciplines')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
