"""add questions table

Revision ID: 59df74d96c05
Revises: 6cc7ace6c16b
Create Date: 2026-04-22 18:27:13.952626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59df74d96c05'
down_revision: Union[str, Sequence[str], None] = '6cc7ace6c16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('id_discipline', sa.Integer(), nullable=False),
    sa.Column('standard_answer', sa.String(), nullable=False),
    sa.Column('question_content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_discipline'], ['disciplines.id_discipline'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_index(op.f('ix_questions_id_question'), 'questions', ['id_question'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_id_question'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
