"""add unique constraint to tests

Revision ID: 6cc7ace6c16b
Revises: 73c16993482c
Create Date: 2026-04-22 18:09:18.548475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc7ace6c16b'
down_revision: Union[str, Sequence[str], None] = '73c16993482c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_discipline_test_uc', 'tests', ['id_discipline', 'test_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_discipline_test_uc', 'tests', type_='unique')
    # ### end Alembic commands ###
