"""create tests table fixed

Revision ID: 73c16993482c
Revises: f4d8d740a9a2
Create Date: 2026-04-22 18:01:43.059543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c16993482c'
down_revision: Union[str, Sequence[str], None] = 'f4d8d740a9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id_test', sa.Integer(), nullable=False),
    sa.Column('test_number', sa.Integer(), nullable=False),
    sa.Column('id_discipline', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_discipline'], ['disciplines.id_discipline'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_test')
    )
    op.create_index(op.f('ix_tests_id_test'), 'tests', ['id_test'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_id_test'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###
