"""add_audio_table

Revision ID: 9bd62225dee7
Revises: cabd242561fc
Create Date: 2026-05-06 18:18:42.786566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd62225dee7'
down_revision: Union[str, Sequence[str], None] = 'cabd242561fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id_audio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('id_result', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['questions.id_question'], ),
    sa.ForeignKeyConstraint(['id_result'], ['exam_results.id_result'], ),
    sa.PrimaryKeyConstraint('id_audio')
    )
    op.create_index(op.f('ix_audio_id_audio'), 'audio', ['id_audio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_id_audio'), table_name='audio')
    op.drop_table('audio')
    # ### end Alembic commands ###
