"""add_groups_and_update_students

Revision ID: afed8d9cf9cb
Revises: b9d030c8296e
Create Date: 2026-05-09 13:58:13.252726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afed8d9cf9cb'
down_revision: Union[str, Sequence[str], None] = 'b9d030c8296e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_index(op.f('ix_groups_group_name'), 'groups', ['group_name'], unique=True)
    op.create_index(op.f('ix_groups_id_group'), 'groups', ['id_group'], unique=False)
    op.add_column('students', sa.Column('id_group', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'groups', ['id_group'], ['id_group'])
    op.drop_column('students', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('group', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'id_group')
    op.drop_index(op.f('ix_groups_id_group'), table_name='groups')
    op.drop_index(op.f('ix_groups_group_name'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
