"""make_standard_answer_nullable

Revision ID: b9d030c8296e
Revises: 9bd62225dee7
Create Date: 2026-05-07 16:01:50.170162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d030c8296e'
down_revision: Union[str, Sequence[str], None] = '9bd62225dee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('complexity_score', sa.Numeric(precision=2, scale=1), nullable=True))
    op.alter_column('questions', 'standard_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'standard_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('questions', 'complexity_score')
    # ### end Alembic commands ###
