"""add_students_table

Revision ID: c868c115084b
Revises: 22dd614885ee
Create Date: 2026-04-10 17:23:32.156515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c868c115084b'
down_revision: Union[str, Sequence[str], None] = '22dd614885ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_student')
    )
    op.create_index(op.f('ix_students_id_student'), 'students', ['id_student'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_id_student'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
