"""use_single_date_field

Revision ID: cabd242561fc
Revises: cfb0eab17447
Create Date: 2026-04-29 19:22:02.945759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cabd242561fc'
down_revision: Union[str, Sequence[str], None] = 'cfb0eab17447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_results', sa.Column('date', sa.TIMESTAMP(), nullable=True))
    op.drop_column('exam_results', 'date_start')
    op.drop_column('exam_results', 'date_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_results', sa.Column('date_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exam_results', sa.Column('date_start', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('exam_results', 'date')
    # ### end Alembic commands ###
